image: node:20
stages:
  - build
  - deploy
cache:
  paths:
    - node_modules/
build:
  stage: build
  script:
    - npm i
    - npm run build --if-present
  artifacts:
    paths:
      - dist/
deploy:
  stage: deploy
  dependencies:
    - build
  before_script:
    - apt-get update -qy
    - apt-get install -y openssh-client sshpass
  script:
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_ROOT 'source ~/.nvm/nvm.sh && cd ./techsupport-be && git pull && npm i && npm run build && pm2 restart 0'
  only:
    - master
